receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5317

processors:
  batch:

exporters:
  prometheus:
    endpoint: collector:8889
    namespace: default
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  # loki:
  #   endpoint: "loki:3100"
  #   tenant_id: "example1"
  #   labels:
  #     attributes:
  #       container_name: ""
  #       container_id: ""
  logging:
    loglevel: debug

extensions:
  health_check:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]