version: "3"

services:
  mongodb_container:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  prometheus:
    image: ${PROMETHEUS_IMG}
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./o11y-backend/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  jaeger-all-in-one:
    image: ${JAEGER_IMG}
    container_name: jaeger
    hostname: jaeger
    restart: always
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
  
  grafana:
    image: ${GRAFANA_IMG}
    container_name: grafana
    hostname: grafana 
    depends_on:
      - jaeger-all-in-one
      - prometheus
      - db
    volumes:
      - ./o11y-backend/grafana-bootstrap.ini:/etc/grafana/grafana.ini
      - ./o11y-backend/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
  
  otel-collector:
    image: ${OTELCOL_IMG}
    container_name: collector
    hostname: collector
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      #- 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 5317:5317 # OTLP gRPC receiver (had to change from 4317 to 5317 in order to avoid conflict with jaeger)
      #- 4318:4318 # OTLP http receiver
      #- 55679:55679 # zpages extension
    depends_on:
      - grafana

  app:
    build:
      dockerfile: Containerfile
    tty: true
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    ports:
      - "8000:8000"
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:5317
      - OTEL_TRACES_SAMPLER=always_on
      - OTEL_IMR_EXPORT_INTERVAL=5000
      - OTEL_METRIC_EXPORT_INTERVAL=5000
      - OTEL_RESOURCE_ATTRIBUTES=service.name=python-app,service.version=1.0,deployment.environment=development

volumes:
  mongodb_data_container:

networks:
  default:
    name: inst-python-apps-using-otel
